services:
    # nginx
    web:
        image: nginx:latest
        container_name: nginx
        ports:
            -   "80:80"
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
    # mysql
    # redis